version: 2
registries:
  gradle-plugin-portal:
    type: maven-repository
    url: https://plugins.gradle.org/m2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - gradle-plugin-portal
    schedule:
      interval: "daily"
    groups:
      fasterxml-jackson:
        patterns: 
          - "com.fasterxml.jackson*"      
      slf4j:
        patterns: 
          - "org.slf4j*"
